In [1]:
import pandas as pd

In [17]:
df = pd.read_csv('circuitos-electorales.csv')

In [18]:
df

,WKT,ID,CIRCUITO_N,COMUNA,BARRIO,TOTAL,MASCULINO,FEMENINO,PERIMETRO,AREA
0,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,1,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05
1,MULTIPOLYGON (((-58.3773566900831 -34.61744732...,2,2,1,SAN TELMO,11365.0,5870.0,5495.0,3045.858735,5.234309e+05
2,MULTIPOLYGON (((-58.3572938809189 -34.59510562...,3,3,1,PUERTO MADERO,702.0,416.0,286.0,14439.585623,4.248033e+06
3,MULTIPOLYGON (((-58.3671229141027 -34.61213671...,4,4,1,PUERTO MADERO,489.0,307.0,182.0,8028.115470,7.773725e+05
4,MULTIPOLYGON (((-58.3835637305124 -34.57823507...,5,5,1,RETIRO,5275.0,3131.0,2144.0,16401.981477,3.262096e+06
...,...,...,...,...,...,...,...,...,...,...
162,MULTIPOLYGON (((-58.4133289404238 -34.64349004...,57,57,4,NUEVA POMPEYA,18768.0,9532.0,9236.0,6341.986116,1.681075e+06
163,MULTIPOLYGON (((-58.4752520574717 -34.66896222...,89,89,8,VILLA LUGANO,46140.0,23699.0,22441.0,10058.062239,4.524566e+06
164,MULTIPOLYGON (((-58.464421436223 -34.660057142...,90,90,8,VILLA LUGANO,42538.0,21474.0,21064.0,10870.018985,4.771794e+06
165,MULTIPOLYGON (((-58.4713146924268 -34.63664464...,112,112,10,FLORESTA,8290.0,3945.0,4345.0,3067.804478,5.421711e+05
166,MULTIPOLYGON (((-58.4740963168322 -34.63043218...,111,111,10,FLORESTA,13465.0,6463.0,7002.0,4035.535929,9.574951e+05

In [33]:
df1 = df.rename(columns={'COMUNA': 'seccion_nombre'})

In [34]:
df1

,WKT,ID,CIRCUITO_N,seccion_nombre,BARRIO,TOTAL,MASCULINO,FEMENINO,PERIMETRO,AREA
0,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,1,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05
1,MULTIPOLYGON (((-58.3773566900831 -34.61744732...,2,2,1,SAN TELMO,11365.0,5870.0,5495.0,3045.858735,5.234309e+05
2,MULTIPOLYGON (((-58.3572938809189 -34.59510562...,3,3,1,PUERTO MADERO,702.0,416.0,286.0,14439.585623,4.248033e+06
3,MULTIPOLYGON (((-58.3671229141027 -34.61213671...,4,4,1,PUERTO MADERO,489.0,307.0,182.0,8028.115470,7.773725e+05
4,MULTIPOLYGON (((-58.3835637305124 -34.57823507...,5,5,1,RETIRO,5275.0,3131.0,2144.0,16401.981477,3.262096e+06
...,...,...,...,...,...,...,...,...,...,...
162,MULTIPOLYGON (((-58.4133289404238 -34.64349004...,57,57,4,NUEVA POMPEYA,18768.0,9532.0,9236.0,6341.986116,1.681075e+06
163,MULTIPOLYGON (((-58.4752520574717 -34.66896222...,89,89,8,VILLA LUGANO,46140.0,23699.0,22441.0,10058.062239,4.524566e+06
164,MULTIPOLYGON (((-58.464421436223 -34.660057142...,90,90,8,VILLA LUGANO,42538.0,21474.0,21064.0,10870.018985,4.771794e+06
165,MULTIPOLYGON (((-58.4713146924268 -34.63664464...,112,112,10,FLORESTA,8290.0,3945.0,4345.0,3067.804478,5.421711e+05
166,MULTIPOLYGON (((-58.4740963168322 -34.63043218...,111,111,10,FLORESTA,13465.0,6463.0,7002.0,4035.535929,9.574951e+05

In [36]:
df1['seccion_nombre'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [39]:
df1['seccion_nombre'] = df1['seccion_nombre'].replace({1:"Comuna 01", 2:'Comuna 02', 3:'Comuna 03', 4:'Comuna 04', 5:'Comuna 05', 6:'Comuna 06', 7:'Comuna 07', 8:'Comuna 08', 9:'Comuna 09', 10:'Comuna 10', 11:'Comuna 11', 12:'Comuna 12', 13:'Comuna 13', 14:'Comuna 14', 15:'Comuna 15'})

In [40]:
df1

,WKT,ID,CIRCUITO_N,seccion_nombre,BARRIO,TOTAL,MASCULINO,FEMENINO,PERIMETRO,AREA
0,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,Comuna 01,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05
1,MULTIPOLYGON (((-58.3773566900831 -34.61744732...,2,2,Comuna 01,SAN TELMO,11365.0,5870.0,5495.0,3045.858735,5.234309e+05
2,MULTIPOLYGON (((-58.3572938809189 -34.59510562...,3,3,Comuna 01,PUERTO MADERO,702.0,416.0,286.0,14439.585623,4.248033e+06
3,MULTIPOLYGON (((-58.3671229141027 -34.61213671...,4,4,Comuna 01,PUERTO MADERO,489.0,307.0,182.0,8028.115470,7.773725e+05
4,MULTIPOLYGON (((-58.3835637305124 -34.57823507...,5,5,Comuna 01,RETIRO,5275.0,3131.0,2144.0,16401.981477,3.262096e+06
...,...,...,...,...,...,...,...,...,...,...
162,MULTIPOLYGON (((-58.4133289404238 -34.64349004...,57,57,Comuna 04,NUEVA POMPEYA,18768.0,9532.0,9236.0,6341.986116,1.681075e+06
163,MULTIPOLYGON (((-58.4752520574717 -34.66896222...,89,89,Comuna 08,VILLA LUGANO,46140.0,23699.0,22441.0,10058.062239,4.524566e+06
164,MULTIPOLYGON (((-58.464421436223 -34.660057142...,90,90,Comuna 08,VILLA LUGANO,42538.0,21474.0,21064.0,10870.018985,4.771794e+06
165,MULTIPOLYGON (((-58.4713146924268 -34.63664464...,112,112,Comuna 10,FLORESTA,8290.0,3945.0,4345.0,3067.804478,5.421711e+05
166,MULTIPOLYGON (((-58.4740963168322 -34.63043218...,111,111,Comuna 10,FLORESTA,13465.0,6463.0,7002.0,4035.535929,9.574951e+05

In [43]:
pd.set_option('mode.chained_assignment', None)

In [44]:
df2 = pd.read_csv('ResultadosElectorales_2023.csv', low_memory=False)

In [45]:
resultado = pd.merge(df1, df2, on='seccion_nombre', how='inner')

In [46]:
resultado

,WKT,ID,CIRCUITO_N,seccion_nombre,BARRIO,TOTAL,MASCULINO,FEMENINO,PERIMETRO,AREA,...,mesa_tipo,mesa_electores,cargo_id,cargo_nombre,agrupacion_id,agrupacion_nombre,lista_numero,lista_nombre,votos_tipo,votos_cantidad
0,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,Comuna 01,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,NULO,0
1,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,Comuna 01,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,IMPUGNADO,0
2,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,Comuna 01,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,RECURRIDO,0
3,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,Comuna 01,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,COMANDO,0
4,MULTIPOLYGON (((-58.3661871461469 -34.62043128...,1,1,Comuna 01,SAN TELMO,11377.0,5695.0,5682.0,4157.175563,7.097216e+05,...,NATIVOS,349,1,PRESIDENTE Y VICE,134,UNION POR LA PATRIA,NaN,NaN,POSITIVO,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850399,MULTIPOLYGON (((-58.4759671316938 -34.59192459...,167,167,Comuna 15,AGRONOMIA,12095.0,5764.0,6331.0,6564.499045,2.122761e+06,...,NATIVOS,343,12,DIPUTADOS/AS DE LA CIUDAD AUTONOMA,0,NaN,0.0,NaN,NULO,1
5850400,MULTIPOLYGON (((-58.4759671316938 -34.59192459...,167,167,Comuna 15,AGRONOMIA,12095.0,5764.0,6331.0,6564.499045,2.122761e+06,...,NATIVOS,343,12,DIPUTADOS/AS DE LA CIUDAD AUTONOMA,0,NaN,0.0,NaN,IMPUGNADO,0
5850401,MULTIPOLYGON (((-58.4759671316938 -34.59192459...,167,167,Comuna 15,AGRONOMIA,12095.0,5764.0,6331.0,6564.499045,2.122761e+06,...,NATIVOS,343,12,DIPUTADOS/AS DE LA CIUDAD AUTONOMA,0,NaN,0.0,NaN,RECURRIDO,0
5850402,MULTIPOLYGON (((-58.4759671316938 -34.59192459...,167,167,Comuna 15,AGRONOMIA,12095.0,5764.0,6331.0,6564.499045,2.122761e+06,...,NATIVOS,343,12,DIPUTADOS/AS DE LA CIUDAD AUTONOMA,0,NaN,0.0,NaN,COMANDO,0
5850403,MULTIPOLYGON (((-58.4759671316938 -34.59192459...,167,167,Comuna 15,AGRONOMIA,12095.0,5764.0,6331.0,6564.499045,2.122761e+06,...,NATIVOS,346,12,DIPUTADOS/AS DE LA CIUDAD AUTONOMA,10803,JUNTOS POR EL CAMBIO,NaN,NaN,POSITIVO,134